package com.java.ravito_plan.common.api.error;

public enum ErrorCode {
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    FOOD_NOT_FOUND,
    BRAND_NOT_FOUND,
    RACE_NOT_FOUND,
    CHECKPOINT_NOT_FOUND,
    CHECKPOINT_FOOD_NOT_FOUND,
    INVALID_CHECKPOINT_ORDER,
    INVALID_ELEVATION,
    RACE_EMPTY_CHECKPOINTS,
    CHECKPOINT_START_TOO_HIGH,
    RACE_WITHOUT_START_OR_FINISH,
    CHECKPOINT_FOOD_NOT_IN_CHECKPOINT,
    CANNOT_CREATE_SEGMENT_WITH_CHECKPOINT,
}
